### ISSUE TITLE
Irritating multiple choice cell grading scheme

### ISSUE THREAD

**Issue by saveli** [DigiKlausur/e2xgrader#58]
The grading scheme for multiple choice cells is irritating, especially for a German university and their judicature.

If you calculate a malus (like you do at the moment) you have to give the option to not answer the question at all, thereby for multiple choice cells you have to have three possible answers per statement: true/false/unanswered.
With unanswered typically defined as true and false unselected.

The situation right now creates unfair situations:
- You know 3 of 4 answers, you don't want to answer the 4th. All 4 were correct, but you only selected 3. Now you receive 2 out of 4 points, punishing you double for not knowing 1 answer.
- More than half of the answers are wrong. You know nothing and thereby skip the question. You still receive points - you are rewarded despite not having thought about the question.

Another valid solution is changing the multiple choice cells to all correct answers have to be selected and all uncorrect answers have to be unselected in order to receive 1 point.

Regarding this, it would help if the feedback shows correctly (un)selected or wrongly (un)selected instead of having to derive the combination with checkbox status and correct/wrong.

Please change this or make it parameterisable.

**Comment by tmetzl** [comment]
I agree with you about the current grading scheme being confusing. When we implemented multiple choice it was for one specific lecture and we took the grading scheme of the professor of said class. 
I think in general it would be better to have an option to change the grading scheme or adapt it to ones needs instead of hardcoding a specific one but I am not sure how to implement this in a user friendly way at the moment.

**Comment by saveli** [comment]
I was about to say provide 2-3 common grading schemes based on university law and let them choose from those in `nbgrader_config.py`, but then `jupyter` won't display those cells correctly, right?

Well then you'd have to implement different multiple choice cells, e.g. `mc-usa, mc-ger, mc-aut`, with respective grading schemes, possibly allowing a selection of those, e.g. `python -m e2xgrader show/hide mc-ger`?

**Comment by tmetzl** [comment]
I think we'll go for the following option:
Instead of having one big autograding function I want to split it into one autograder for code, one for multiple choice, one for general markdown etc. Then we could make these configurable in the ``nbgrader_config.py`` and everyone can just add the grading scheme they like.
